version: "3.3"
services:
  spark-master:
    image: ls12styler/spark:2.4.3
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    networks: 
      - spark-network
    command: "start-master.sh --ip spark-master --webui-port 8080 --port 7077"
  spark-worker:
    image: ls12styler/spark:2.4.3
    depends_on:
      - spark-master
    ports:
      - 8080
    networks: 
      - spark-network
    command: "start-worker.sh --webui-port 8080 spark://spark-master:7077"
    volumes:
      - "./:/local"
networks:
  spark-network:
    driver: bridge
    ipam:
      driver: default
